/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordRouteImport } from './routes/record'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminQuizzesRouteImport } from './routes/admin/quizzes'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CertificatesCodeRouteImport } from './routes/certificates/$code'
import { Route as CourseSlugRouteImport } from './routes/course/$slug'
import { Route as QuizIdRouteImport } from './routes/quiz/$id'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminCoursesIdRouteImport } from './routes/admin/courses/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuizzesRoute = AdminQuizzesRouteImport.update({
  id: '/admin/quizzes',
  path: '/admin/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesCodeRoute = CertificatesCodeRouteImport.update({
  id: '/certificates/$code',
  path: '/certificates/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const AdminCoursesIdRoute = AdminCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/records': typeof RecordsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/course/$slug': typeof CourseSlugRoute
  '/quiz/$id': typeof QuizIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/records': typeof RecordsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/course/$slug': typeof CourseSlugRoute
  '/quiz/$id': typeof QuizIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/records': typeof RecordsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/certificates/$code': typeof CertificatesCodeRoute
  '/course/$slug': typeof CourseSlugRoute
  '/quiz/$id': typeof QuizIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile'
    | '/record'
    | '/records'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/quizzes'
    | '/admin/settings'
    | '/admin/users'
    | '/certificates/$code'
    | '/course/$slug'
    | '/quiz/$id'
    | '/admin/'
    | '/admin/courses/$id'
    | '/admin/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/record'
    | '/records'
    | '/admin/analytics'
    | '/admin/quizzes'
    | '/admin/settings'
    | '/admin/users'
    | '/certificates/$code'
    | '/course/$slug'
    | '/quiz/$id'
    | '/admin'
    | '/admin/courses/$id'
    | '/admin/courses'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/profile'
    | '/record'
    | '/records'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/quizzes'
    | '/admin/settings'
    | '/admin/users'
    | '/certificates/$code'
    | '/course/$slug'
    | '/quiz/$id'
    | '/admin/'
    | '/admin/courses/$id'
    | '/admin/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  RecordRoute: typeof RecordRoute
  RecordsRoute: typeof RecordsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminQuizzesRoute: typeof AdminQuizzesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CertificatesCodeRoute: typeof CertificatesCodeRoute
  CourseSlugRoute: typeof CourseSlugRoute
  QuizIdRoute: typeof QuizIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quizzes': {
      id: '/admin/quizzes'
      path: '/admin/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AdminQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$code': {
      id: '/certificates/$code'
      path: '/certificates/$code'
      fullPath: '/certificates/$code'
      preLoaderRoute: typeof CertificatesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/admin/courses/$id': {
      id: '/admin/courses/$id'
      path: '/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AdminCoursesIdRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
  }
}

interface AdminCoursesRouteChildren {
  AdminCoursesIdRoute: typeof AdminCoursesIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesIdRoute: AdminCoursesIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  RecordRoute: RecordRoute,
  RecordsRoute: RecordsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminQuizzesRoute: AdminQuizzesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CertificatesCodeRoute: CertificatesCodeRoute,
  CourseSlugRoute: CourseSlugRoute,
  QuizIdRoute: QuizIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
